version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
        - POSTGRES_USER=alterdata
        - POSTGRES_PASSWORD=alterdata
        - POSTGRES_DB=alterdata_db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      ENV: development
    ports:
      - "8000:8000"

volumes:
  postgres_data: