services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/app
    environment:
      ENV: development
    ports:
      - "8000:8000"