version: '3'

services:
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
        - POSTGRES_USER=alterdata
        - POSTGRES_PASSWORD=alterdata
        - POSTGRES_DB=alterdata_db

volumes:
  postgres_data: