services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      ENV: production
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000